// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/avatar/user/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/avatar/user/[id]').default>>>>
    }
    '/api/avatars': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/avatars').default>>>>
    }
    '/api/celebration': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/celebration.post').default>>>>
    }
    '/api/celebration/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/celebration/[id]').default>>>>
    }
    '/api/celebrations/author/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/celebrations/author/[id]').default>>>>
    }
    '/api/celebrations/guest/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/celebrations/guest/[id]').default>>>>
    }
    '/api/guest': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guest.post').default>>>>
    }
    '/api/guest/:user/:celebration': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guest/[user]/[celebration].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guest/[user]/[celebration].post').default>>>>
    }
    '/api/guests/celebration/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guests/celebration/[id]').default>>>>
    }
    '/api/user/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/[id].delete').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/[id]').default>>>>
    }
    '/api/users': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}