
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AlertCelebrationCreation': typeof import("../components/AlertCelebrationCreation.vue")['default']
    'AlertDeleteAccount': typeof import("../components/AlertDeleteAccount.vue")['default']
    'AlertDeleteSuccess': typeof import("../components/AlertDeleteSuccess.vue")['default']
    'AlertLoggedIn': typeof import("../components/AlertLoggedIn.vue")['default']
    'AlertNotLoggedIn': typeof import("../components/AlertNotLoggedIn.vue")['default']
    'AlertRegistration': typeof import("../components/AlertRegistration.vue")['default']
    'CelebrationCard': typeof import("../components/CelebrationCard.vue")['default']
    'CelebrationCardPast': typeof import("../components/CelebrationCardPast.vue")['default']
    'FooterPage': typeof import("../components/FooterPage.vue")['default']
    'MenubarCompo': typeof import("../components/MenubarCompo.vue")['default']
    'ModifyAvatar': typeof import("../components/ModifyAvatar.vue")['default']
    'ShareInvitation': typeof import("../components/ShareInvitation.vue")['default']
    'TheWelcome': typeof import("../components/TheWelcome.vue")['default']
    'WelcomeItem': typeof import("../components/WelcomeItem.vue")['default']
    'IconsIconCommunity': typeof import("../components/icons/IconCommunity.vue")['default']
    'IconsIconDocumentation': typeof import("../components/icons/IconDocumentation.vue")['default']
    'IconsIconEcosystem': typeof import("../components/icons/IconEcosystem.vue")['default']
    'IconsIconGitHub': typeof import("../components/icons/IconGitHub.vue")['default']
    'IconsIconSupport': typeof import("../components/icons/IconSupport.vue")['default']
    'IconsIconTooling': typeof import("../components/icons/IconTooling.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtIcon': typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAlertCelebrationCreation': typeof import("../components/AlertCelebrationCreation.vue")['default']
    'LazyAlertDeleteAccount': typeof import("../components/AlertDeleteAccount.vue")['default']
    'LazyAlertDeleteSuccess': typeof import("../components/AlertDeleteSuccess.vue")['default']
    'LazyAlertLoggedIn': typeof import("../components/AlertLoggedIn.vue")['default']
    'LazyAlertNotLoggedIn': typeof import("../components/AlertNotLoggedIn.vue")['default']
    'LazyAlertRegistration': typeof import("../components/AlertRegistration.vue")['default']
    'LazyCelebrationCard': typeof import("../components/CelebrationCard.vue")['default']
    'LazyCelebrationCardPast': typeof import("../components/CelebrationCardPast.vue")['default']
    'LazyFooterPage': typeof import("../components/FooterPage.vue")['default']
    'LazyMenubarCompo': typeof import("../components/MenubarCompo.vue")['default']
    'LazyModifyAvatar': typeof import("../components/ModifyAvatar.vue")['default']
    'LazyShareInvitation': typeof import("../components/ShareInvitation.vue")['default']
    'LazyTheWelcome': typeof import("../components/TheWelcome.vue")['default']
    'LazyWelcomeItem': typeof import("../components/WelcomeItem.vue")['default']
    'LazyIconsIconCommunity': typeof import("../components/icons/IconCommunity.vue")['default']
    'LazyIconsIconDocumentation': typeof import("../components/icons/IconDocumentation.vue")['default']
    'LazyIconsIconEcosystem': typeof import("../components/icons/IconEcosystem.vue")['default']
    'LazyIconsIconGitHub': typeof import("../components/icons/IconGitHub.vue")['default']
    'LazyIconsIconSupport': typeof import("../components/icons/IconSupport.vue")['default']
    'LazyIconsIconTooling': typeof import("../components/icons/IconTooling.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtIcon': typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AlertCelebrationCreation: typeof import("../components/AlertCelebrationCreation.vue")['default']
export const AlertDeleteAccount: typeof import("../components/AlertDeleteAccount.vue")['default']
export const AlertDeleteSuccess: typeof import("../components/AlertDeleteSuccess.vue")['default']
export const AlertLoggedIn: typeof import("../components/AlertLoggedIn.vue")['default']
export const AlertNotLoggedIn: typeof import("../components/AlertNotLoggedIn.vue")['default']
export const AlertRegistration: typeof import("../components/AlertRegistration.vue")['default']
export const CelebrationCard: typeof import("../components/CelebrationCard.vue")['default']
export const CelebrationCardPast: typeof import("../components/CelebrationCardPast.vue")['default']
export const FooterPage: typeof import("../components/FooterPage.vue")['default']
export const MenubarCompo: typeof import("../components/MenubarCompo.vue")['default']
export const ModifyAvatar: typeof import("../components/ModifyAvatar.vue")['default']
export const ShareInvitation: typeof import("../components/ShareInvitation.vue")['default']
export const TheWelcome: typeof import("../components/TheWelcome.vue")['default']
export const WelcomeItem: typeof import("../components/WelcomeItem.vue")['default']
export const IconsIconCommunity: typeof import("../components/icons/IconCommunity.vue")['default']
export const IconsIconDocumentation: typeof import("../components/icons/IconDocumentation.vue")['default']
export const IconsIconEcosystem: typeof import("../components/icons/IconEcosystem.vue")['default']
export const IconsIconGitHub: typeof import("../components/icons/IconGitHub.vue")['default']
export const IconsIconSupport: typeof import("../components/icons/IconSupport.vue")['default']
export const IconsIconTooling: typeof import("../components/icons/IconTooling.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtIcon: typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAlertCelebrationCreation: typeof import("../components/AlertCelebrationCreation.vue")['default']
export const LazyAlertDeleteAccount: typeof import("../components/AlertDeleteAccount.vue")['default']
export const LazyAlertDeleteSuccess: typeof import("../components/AlertDeleteSuccess.vue")['default']
export const LazyAlertLoggedIn: typeof import("../components/AlertLoggedIn.vue")['default']
export const LazyAlertNotLoggedIn: typeof import("../components/AlertNotLoggedIn.vue")['default']
export const LazyAlertRegistration: typeof import("../components/AlertRegistration.vue")['default']
export const LazyCelebrationCard: typeof import("../components/CelebrationCard.vue")['default']
export const LazyCelebrationCardPast: typeof import("../components/CelebrationCardPast.vue")['default']
export const LazyFooterPage: typeof import("../components/FooterPage.vue")['default']
export const LazyMenubarCompo: typeof import("../components/MenubarCompo.vue")['default']
export const LazyModifyAvatar: typeof import("../components/ModifyAvatar.vue")['default']
export const LazyShareInvitation: typeof import("../components/ShareInvitation.vue")['default']
export const LazyTheWelcome: typeof import("../components/TheWelcome.vue")['default']
export const LazyWelcomeItem: typeof import("../components/WelcomeItem.vue")['default']
export const LazyIconsIconCommunity: typeof import("../components/icons/IconCommunity.vue")['default']
export const LazyIconsIconDocumentation: typeof import("../components/icons/IconDocumentation.vue")['default']
export const LazyIconsIconEcosystem: typeof import("../components/icons/IconEcosystem.vue")['default']
export const LazyIconsIconGitHub: typeof import("../components/icons/IconGitHub.vue")['default']
export const LazyIconsIconSupport: typeof import("../components/icons/IconSupport.vue")['default']
export const LazyIconsIconTooling: typeof import("../components/icons/IconTooling.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtIcon: typeof import("../node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
