// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/12/2024 22:54:22
const configMerger = require("C:/Users/ghiso/Documents/RNCP/Festify/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/ghiso/Documents/RNCP/Festify/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ghiso/Documents/RNCP/Festify/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ghiso/Documents/RNCP/Festify/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ghiso/Documents/RNCP/Festify/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ghiso/Documents/RNCP/Festify/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ghiso/Documents/RNCP/Festify/plugins/**/*.{js,ts,mjs}","C:/Users/ghiso/Documents/RNCP/Festify/composables/**/*.{js,ts,mjs}","C:/Users/ghiso/Documents/RNCP/Festify/utils/**/*.{js,ts,mjs}","C:/Users/ghiso/Documents/RNCP/Festify/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ghiso/Documents/RNCP/Festify/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ghiso/Documents/RNCP/Festify/app.config.{js,ts,mjs}"] } }));

module.exports = config
